# Generated by Django 4.0.3 on 2022-04-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FamiliaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='fecha_nacimiento',
        ),
    ]
